import { Language } from '../types';

export interface Translations {
  // Common
  appName: string;
  appSubtitle: string;
  save: string;
  cancel: string;
  delete: string;
  edit: string;
  close: string;
  search: string;
  searchPlaceholder: string;
  filter: string;
  all: string;
  actions: string;
  print: string;
  downloadPdf: string;
  shareWhatsApp: string;
  status: string;
  date: string;
  deliveryDate: string;
  returnDate: string;
  created: string;
  notes: string;
  details: string;
  back: string;
  yes: string;
  no: string;
  loading: string;
  success: string;
  savedSuccessfully: string;
  deletedSuccessfully: string;
  confirmDelete: string;
  areYouSure: string;
  noDataFound: string;
  viewDetails: string;
  required: string;
  optional: string;

  // Nav tabs
  dashboard: string;
  newOrder: string;
  customers: string;
  fabrics: string;
  fabricInventory: string;
  products: string;
  productsInventory: string;
  designAndSettings: string;
  designTemplatesNav: string;
  measurementSettingsNav: string;
  shopProfileNav: string;
  backupNav: string;
  menu: string;

  // Dashboard stats
  totalOrders: string;
  todaysOrders: string;
  pendingDeliveries: string;
  totalMonthlyRevenue: string;
  pendingOrders: string;
  inProgressOrders: string;
  readyOrders: string;
  deliveredOrders: string;
  totalRevenue: string;
  totalPaid: string;
  totalBalanceDue: string;

  // Order status
  orderStatus: string;
  statusPending: string;
  statusInProgress: string;
  statusReady: string;
  statusDelivered: string;
  quickStatus: string;
  markPending: string;
  markInProgress: string;
  markReady: string;
  markDelivered: string;

  // Sorting
  sortBy: string;
  sortNewest: string;
  sortOldest: string;
  sortDeliveryNearest: string;
  sortDeliveryFurthest: string;
  viewCustomerHistory: string;

  // Payment status
  paymentStatus: string;
  paid: string;
  partial: string;
  unpaid: string;
  totalAmount: string;
  paidAmount: string;
  balanceRemaining: string;
  advancePayment: string;
  updatePayment: string;

  // Order Form
  customerInfo: string;
  customerName: string;
  contactNumber: string;
  whatsappNumber: string;
  orderNumber: string;
  autoGenerated: string;
  garmentType: string;
  quantity: string;
  orderSummary: string;
  measurements: string;
  designAndStyle: string;
  specialNotes: string;
  saveOrder: string;
  saveAndPrint: string;
  loadCustomerMeasurements: string;
  existingCustomerFound: string;
  newCustomerAutoSaved: string;
  quickFill: string;

  // Fabric Inventory
  addFabric: string;
  editFabric: string;
  fabricName: string;
  fabricCode: string;
  fabricType: string;
  fabricColor: string;
  pricePerMeter: string;
  stockMeters: string;
  inStock: string;
  lowStock: string;
  outOfStock: string;
  selectFabric: string;
  customerFabric: string;
  fabricUsed: string;
  selectFromInventory: string;
  fabricDetails: string;
  searchFabricPlaceholder: string;
  meters: string;

  // Garment Types
  perahanTunban: string;
  waistcoat: string;
  suit: string;
  coatKorti: string;
  kameezShalwar: string;
  kurta: string;
  otherGarment: string;

  // Measurements labels
  qad: string; // قد (Length)
  shana: string; // شانه (Shoulder)
  asteen: string; // آستین (Sleeve)
  yakhan: string; // یخن / کالر (Collar/Neck)
  chati: string; // چاتی / سینه (Chest)
  baghal: string; // بغل (Armpit/Underarm)
  kamar: string; // کمر (Waist)
  daman: string; // دامن (Hem/Daman)
  tunban: string; // تنبان / پرتوګ (Trouser Length)
  pacha: string; // پاچه (Trouser Bottom)
  surin: string; // سورین (Hip/Seat)
  machDast: string; // مچ دست (Wrist)
  unitInches: string;

  // Customers View
  customersList: string;
  customerProfile: string;
  totalOrdersCount: string;
  lastOrderDate: string;
  savedMeasurements: string;
  createNewOrderForCustomer: string;
  customerHistory: string;
  searchCustomersPlaceholder: string;
  addNewCustomer: string;
  editCustomer: string;

  // Design Templates & Settings
  designTemplates: string;
  manageDesignCategories: string;
  addCategory: string;
  categoryTitle: string;
  addOption: string;
  optionName: string;
  measurementSettings: string;
  addMeasurementField: string;
  shopProfile: string;
  shopName: string;
  shopAddress: string;
  phones: string;
  receiptFooter: string;
  currency: string;
  backupAndRestore: string;
  exportBackup: string;
  importBackup: string;
  resetDemoData: string;
  backupDescription: string;

  // Receipt / Slip
  tailorReceipt: string;
  tailorWorkSlip: string;
  customerReceipt: string;
  bothSlips: string;
  printTailorSlip: string;
  printCustomerReceipt: string;
  downloadTailorPdf: string;
  downloadCustomerPdf: string;
  measurementSlip: string;
  billBarcode: string;
  phoneBarcode: string;
  specs: string;
  shape: string;
  orderTakingDate: string;
  totalBill: string;
  totalRemaining: string;
  cabinetAndQty: string;
  customerAndGarment: string;
  a6Paper: string;
  item: string;
  qty: string;
  price: string;
  thankYouMessage: string;

  // Products & Retail Inventory
  shoes: string;
  watches: string;
  perfume: string;
  purchasePrice: string;
  sellingPrice: string;
  stockQuantity: string;
  lowStockThreshold: string;
  sellItem: string;
  sellProduct: string;
  recordSale: string;
  salesHistory: string;
  profit: string;
  brand: string;
  vendor: string;
  category: string;
  manageVendorsCategories: string;
  createProductListing: string;
  newInventoryEntry: string;
  addRemoveReusableValues: string;
  addVendor: string;
  addBrand: string;
  itemName: string;
  selectVendor: string;
  selectCategory: string;
  selectBrand: string;
  decidePriceNotice: string;
  addProduct: string;
  editProduct: string;
  productName: string;
  initialStock: string;
  sku: string;
  description: string;
  allCategories: string;
  product: string;
  customer: string;
  searchProductPlaceholder: string;
  noProductsFound: string;
  quantityToSell: string;
  confirmSale: string;
  updateProduct: string;
  salesHistoryNav: string;
  newSale: string;
  lowStockAlert: string;
  configurableThreshold: string;
  revenueOverview7Days: string;
  dailyRevenue: string;
  orderRevenue: string;
  productSalesRevenue: string;
  customerHistoryDetails: string;
  tailorOrdersHistory: string;
  retailPurchasesHistory: string;
  totalSpent: string;

  // Login & Auth
  loginTitle: string;
  loginSubtitle: string;
  email: string;
  password: string;
  signInBtn: string;
  signOut: string;
  invalidCredentials: string;
  quickLoginAdmin: string;
  loggedInAs: string;
  adminAccount: string;
  printFormat: string;
  standardA4: string;
  thermal58: string;
  thermal80: string;

  // Garment Categories & Dynamic Measurement Settings
  garmentTypesNav: string;
  garmentCategory: string;
  allGarments: string;
  editMeasurementField: string;
  fieldNameEn: string;
  fieldNameFa: string;
  fieldNamePs: string;
  defaultVal: string;
  stepIncrement: string;
  isRequired: string;
  addDesignCategory: string;
  editDesignCategory: string;
  optionNameEn: string;
  optionNameFa: string;
  optionNamePs: string;
  garmentTypeSelect: string;
  itemPeranTonban: string;
  itemWasoat: string;
  itemShirt: string;
  itemKurta: string;
  itemTwoPiece: string;
  itemSuit: string;
  itemCoatKorti: string;
  itemOther: string;
  saveMeasurementFieldBtn: string;
  selectGarmentTypePrompt: string;
  garmentSpecificFields: string;
  manageGarmentsSubTab: string;
  filterByGarment: string;
  addGarmentType: string;
  editGarmentType: string;
  garmentTypeNameEn: string;
  garmentTypeNameFa: string;
  garmentTypeNamePs: string;

  // Reports & Business Streams
  reportsNav: string;
  tailorRevenue: string;
  tailorCollected: string;
  tailorBalance: string;
  tailorProfit: string;
  retailRevenue: string;
  retailCollected: string;
  retailCost: string;
  retailProfit: string;
  totalShopRevenue: string;
  totalShopCollected: string;
  totalShopProfit: string;
  tailoringStream: string;
  retailStream: string;
  combinedStream: string;
  moneyCollectedBreakdown: string;
  retailRecords: string;
  viewRetailSales: string;
  allRecords: string;
  tailorRecords: string;
  quickPrintSlip: string;
  totalRetailSales: string;
  todaysRetailRevenue: string;
  customSellingPrice: string;

  // Expenses
  expenses: string;
  expensesNav: string;
  addExpense: string;
  editExpense: string;
  expenseTitle: string;
  expenseAmount: string;
  expenseDate: string;
  spentBy: string;
  expenseCategory: string;
  paymentMethod: string;
  totalExpenses: string;
  thisMonthExpenses: string;
  todayExpenses: string;
  averageExpense: string;
  expenseReceiptNo: string;
  expenseNotes: string;
  categoryRent: string;
  categoryUtilities: string;
  categoryMaterials: string;
  categoryMaintenance: string;
  categoryFood: string;
  categorySalaries: string;
  categoryTransport: string;
  categoryMarketing: string;
  categoryOther: string;
  deleteExpense: string;
  deleteExpenseConfirmTitle: string;
  deleteExpenseConfirmMessage: string;
  moneyAdjustedNotice: string;
  moneyRefundedToast: string;
  netShopBalance: string;
  netProfit: string;
  totalInflows: string;
}

export const translations: Record<Language, Translations> = {
  en: {
    appName: 'MUJEEB AFGHAN FASHION HOUSE',
    appSubtitle: 'Orders, Measurements & Customer Management',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    search: 'Search',
    searchPlaceholder: 'Search by Customer Name, Contact, Order #, or Date...',
    filter: 'Filter',
    all: 'All',
    actions: 'Actions',
    print: 'Print Slip',
    downloadPdf: 'Download PDF',
    shareWhatsApp: 'Send via WhatsApp',
    status: 'Status',
    date: 'Date',
    deliveryDate: 'Delivery Date',
    returnDate: 'Return Date',
    created: 'Created',
    notes: 'Notes',
    details: 'Details',
    back: 'Back',
    yes: 'Yes',
    no: 'No',
    loading: 'Loading...',
    success: 'Success',
    savedSuccessfully: 'Saved successfully',
    deletedSuccessfully: 'Deleted successfully',
    confirmDelete: 'Are you sure you want to delete this record?',
    areYouSure: 'This action cannot be undone.',
    noDataFound: 'No records found',
    viewDetails: 'View Details',
    required: 'Required',
    optional: 'Optional',

    dashboard: 'Orders Dashboard',
    newOrder: 'New Order',
    customers: 'Customer Directory',
    fabrics: 'Fabric Inventory',
    fabricInventory: 'Fabric Inventory',
    products: 'Products & Retail',
    productsInventory: 'Products Inventory',
    designAndSettings: 'Design & Settings',
    designTemplatesNav: 'Design Templates',
    measurementSettingsNav: 'Measurement Fields',
    shopProfileNav: 'Shop Profile & Slip',
    backupNav: 'Backup & Restore',
    menu: 'Main Navigation',

    totalOrders: 'Total Orders',
    todaysOrders: "Total Today's Orders",
    pendingDeliveries: 'Pending Deliveries',
    totalMonthlyRevenue: 'Total Monthly Revenue',
    pendingOrders: 'Pending',
    inProgressOrders: 'In Progress',
    readyOrders: 'Ready for Pickup',
    deliveredOrders: 'Delivered',
    totalRevenue: 'Total Value',
    totalPaid: 'Collected Paid',
    totalBalanceDue: 'Balance Due',

    orderStatus: 'Order Status',
    statusPending: 'Pending',
    statusInProgress: 'In-Progress',
    statusReady: 'Ready',
    statusDelivered: 'Delivered',
    quickStatus: 'Quick Status',
    markPending: 'Change to Pending',
    markInProgress: 'Change to In Progress',
    markReady: 'Change to Ready',
    markDelivered: 'Change to Delivered',

    sortBy: 'Sort By',
    sortNewest: 'Newest First',
    sortOldest: 'Oldest First',
    sortDeliveryNearest: 'Upcoming Delivery (Earliest)',
    sortDeliveryFurthest: 'Delivery Date (Furthest)',
    viewCustomerHistory: 'View Customer History',

    paymentStatus: 'Payment Status',
    paid: 'Paid in Full',
    partial: 'Partial / Advance',
    unpaid: 'Unpaid',
    totalAmount: 'Total Amount',
    paidAmount: 'Paid / Advance',
    balanceRemaining: 'Remaining Balance',
    advancePayment: 'Advance Payment',
    updatePayment: 'Update Payment',

    customerInfo: 'Customer Information',
    customerName: 'Customer Name',
    contactNumber: 'Phone / Contact Number',
    whatsappNumber: 'WhatsApp Number',
    orderNumber: 'Order Number',
    autoGenerated: 'Auto-generated',
    garmentType: 'Garment Type',
    quantity: 'Quantity',
    orderSummary: 'Order Summary',
    measurements: 'Measurements (Inches)',
    designAndStyle: 'Design & Style Options',
    specialNotes: 'Special Instructions / Tailoring Notes',
    saveOrder: 'Save Order',
    saveAndPrint: 'Save & Print Slip',
    loadCustomerMeasurements: 'Load previous measurements',
    existingCustomerFound: 'Existing customer identified! Measurements ready.',
    newCustomerAutoSaved: 'New customer will be automatically added to directory.',
    quickFill: 'Quick Fill',

    addFabric: 'Add Fabric',
    editFabric: 'Edit Fabric',
    fabricName: 'Fabric Name',
    fabricCode: 'Fabric Code',
    fabricType: 'Fabric Material / Type',
    fabricColor: 'Color / Shade',
    pricePerMeter: 'Price / Meter',
    stockMeters: 'Stock in Stock',
    inStock: 'In Stock',
    lowStock: 'Low Stock',
    outOfStock: 'Out of Stock',
    selectFabric: 'Select Fabric',
    customerFabric: "Customer's Own Fabric",
    fabricUsed: 'Fabric Used (Meters)',
    selectFromInventory: 'Select from Shop Inventory',
    fabricDetails: 'Fabric Details',
    searchFabricPlaceholder: 'Search fabric by name, code, type, or color...',
    meters: 'm',

    perahanTunban: 'Perahan Tunban (Afghan Suit)',
    waistcoat: 'Waistcoat (Wasqat)',
    suit: 'Suit (Drishi)',
    coatKorti: 'Coat / Jacket (Korti)',
    kameezShalwar: 'Kameez Shalwar',
    kurta: 'Kurta',
    otherGarment: 'Custom Garment',

    qad: 'Length (Qad / قد)',
    shana: 'Shoulder (Shana / شانه)',
    asteen: 'Sleeve (Asteen / آستین)',
    yakhan: 'Collar/Neck (Yakhan / یخن)',
    chati: 'Chest (Chati / چاتی)',
    baghal: 'Armpit (Baghal / بغل)',
    kamar: 'Waist (Kamar / کمر)',
    daman: 'Daman / Hem (دامن)',
    tunban: 'Trouser Length (تنبان)',
    pacha: 'Bottom / Pacha (پاچه)',
    surin: 'Seat / Hip (سورین)',
    machDast: 'Wrist (مچ دست)',
    unitInches: 'in',

    customersList: 'Customer Directory',
    customerProfile: 'Customer Profile',
    totalOrdersCount: 'Total Orders',
    lastOrderDate: 'Last Order',
    savedMeasurements: 'Saved Measurements',
    createNewOrderForCustomer: 'New Order with These Measurements',
    customerHistory: 'Order History',
    searchCustomersPlaceholder: 'Search by Customer Name, Phone, or Order #...',
    addNewCustomer: 'Add Customer',
    editCustomer: 'Edit Customer',

    designTemplates: 'Design Templates & Styles',
    manageDesignCategories: 'Customize Design Categories & Presets',
    addCategory: 'Add Design Category',
    categoryTitle: 'Category Title',
    addOption: 'Add Style Option',
    optionName: 'Style Option Name',
    measurementSettings: 'Measurement Fields Settings',
    addMeasurementField: 'Add Custom Measurement Field',
    shopProfile: 'Shop Profile & Receipt Info',
    shopName: 'Shop Name',
    shopAddress: 'Shop Address',
    phones: 'Phone Numbers',
    receiptFooter: 'Receipt Footer Text',
    currency: 'Currency Symbol',
    backupAndRestore: 'Backup & Restore Database',
    exportBackup: 'Download JSON Backup',
    importBackup: 'Restore JSON Backup',
    resetDemoData: 'Reset Demo Data',
    backupDescription: 'Export your entire tailor shop database (all orders, customer records, design templates) as a backup file.',

    tailorReceipt: 'Tailoring Receipt & Measurement Slip',
    tailorWorkSlip: 'Tailor Production Slip',
    customerReceipt: 'Customer Receipt',
    bothSlips: 'Both Slips (Tailor + Customer)',
    printTailorSlip: 'Print Tailor Slip',
    printCustomerReceipt: 'Print Customer Receipt',
    downloadTailorPdf: 'Download Tailor PDF',
    downloadCustomerPdf: 'Download Customer PDF',
    measurementSlip: 'Measurement Slip',
    billBarcode: 'Order Barcode',
    phoneBarcode: 'Customer Barcode',
    specs: 'Specifications',
    shape: 'Style / Shape',
    orderTakingDate: 'Order Date',
    totalBill: 'Total Amount',
    totalRemaining: 'Total Balance',
    cabinetAndQty: 'Qty & Cabinet',
    customerAndGarment: 'Customer : Garment',
    a6Paper: 'A6 Paper',
    item: 'Item',
    qty: 'Qty',
    price: 'Price',
    thankYouMessage: 'Thank you for choosing our tailor shop!',

    // Products & Retail Inventory
    shoes: 'Shoes',
    watches: 'Watches',
    perfume: 'Perfume',
    purchasePrice: 'Purchase Price',
    sellingPrice: 'Selling Price',
    stockQuantity: 'Stock Quantity',
    lowStockThreshold: 'Low Stock Alert',
    sellItem: 'Sell Item',
    sellProduct: 'Sell Product',
    recordSale: 'Record Retail Sale',
    salesHistory: 'Sales History',
    profit: 'Profit / Margin',
    brand: 'Brand / Company',
    vendor: 'Vendor / Supplier',
    category: 'Category',
    manageVendorsCategories: 'Manage vendors and categories',
    createProductListing: 'Create a product listing',
    newInventoryEntry: 'New inventory entry',
    addRemoveReusableValues: 'Add or remove reusable values',
    addVendor: 'Add Vendor',
    addBrand: 'Add Brand',
    itemName: 'Item Name',
    selectVendor: 'Select vendor...',
    selectCategory: 'Select category...',
    selectBrand: 'Select brand...',
    decidePriceNotice: 'Selling price is decided at time of sale',
    addProduct: 'Add New Product',
    editProduct: 'Edit Product',
    productName: 'Product Name',
    initialStock: 'Initial Stock Quantity',
    sku: 'Item Code / SKU',
    description: 'Description & Details',
    allCategories: 'All Categories',
    product: 'Product',
    customer: 'Customer',
    searchProductPlaceholder: 'Search products by name, brand, SKU...',
    noProductsFound: 'No products found matching your search',
    quantityToSell: 'Quantity to Sell',
    confirmSale: 'Confirm Sale',
    updateProduct: 'Update Product',
    salesHistoryNav: 'Sales History',
    newSale: 'Make a New Sale',
    lowStockAlert: 'Low Stock Alert',
    configurableThreshold: 'Alert Threshold',
    revenueOverview7Days: '7-Day Revenue Overview (Orders vs Retail Sales)',
    dailyRevenue: 'Daily Revenue',
    orderRevenue: 'Tailoring Orders Revenue',
    productSalesRevenue: 'Retail Sales Revenue',
    customerHistoryDetails: 'Customer Transaction & Order History',
    tailorOrdersHistory: 'Tailoring Orders History',
    retailPurchasesHistory: 'Retail Products Purchased',
    totalSpent: 'Total Customer Spend',

    loginTitle: 'Sign In to MUJEEB AFGHAN FASHION HOUSE',
    loginSubtitle: 'Enter your credentials to access the management portal',
    email: 'Email Address',
    password: 'Password',
    signInBtn: 'Sign In',
    signOut: 'Sign Out',
    invalidCredentials: 'Invalid email or password. Please check your credentials.',
    quickLoginAdmin: 'Autofill Admin Login',
    loggedInAs: 'Signed in as',
    adminAccount: 'Master Tailor Admin',
    printFormat: 'Print format',
    standardA4: 'Standard A4',
    thermal58: 'Thermal 58 mm',
    thermal80: 'Thermal 80 mm',

    garmentTypesNav: 'Garment Categories',
    garmentCategory: 'Garment Category',
    allGarments: 'All Garments / Universal',
    editMeasurementField: 'Edit Measurement Field',
    fieldNameEn: 'Field Name (English)',
    fieldNameFa: 'Field Name (Dari)',
    fieldNamePs: 'Field Name (Pashto)',
    defaultVal: 'Default Value',
    stepIncrement: 'Step (Increment)',
    isRequired: 'Required Field',
    addDesignCategory: 'Add Design Category',
    editDesignCategory: 'Edit Design Category',
    optionNameEn: 'Option Name (English)',
    optionNameFa: 'Option Name (Dari)',
    optionNamePs: 'Option Name (Pashto)',
    garmentTypeSelect: 'Select Garment Type',
    itemPeranTonban: 'Perahan / Tumban (Afghan Suit)',
    itemWasoat: 'Wescott / Wasqat',
    itemShirt: 'Shirt (Long Sleeve)',
    itemKurta: 'Kurta Style',
    itemTwoPiece: 'Two Piece',
    itemSuit: 'Suit (Drishi / Coat & Pant)',
    itemCoatKorti: 'Coat / Korti',
    itemOther: 'Custom / Other',
    saveMeasurementFieldBtn: 'Save Measurement Field',
    selectGarmentTypePrompt: 'What would you like to make for the customer?',
    garmentSpecificFields: 'Garment-Specific Measurement & Design Fields',
    manageGarmentsSubTab: 'Garment Types',
    filterByGarment: 'Filter by Garment Type',
    addGarmentType: 'Add New Garment Type',
    editGarmentType: 'Edit Garment Type',
    garmentTypeNameEn: 'Garment Name (English)',
    garmentTypeNameFa: 'Garment Name (Dari)',
    garmentTypeNamePs: 'Garment Name (Pashto)',

    // Reports & Business Streams
    reportsNav: 'Reports & Analytics',
    tailorRevenue: 'Tailoring Revenue / Billed',
    tailorCollected: 'Tailoring Money Collected',
    tailorBalance: 'Tailoring Outstanding',
    tailorProfit: 'Tailoring Net Profit',
    retailRevenue: 'Retail Revenue',
    retailCollected: 'Retail Money Collected',
    retailCost: 'Retail Cost (Purchase)',
    retailProfit: 'Retail Net Profit',
    totalShopRevenue: 'Total Combined Revenue',
    totalShopCollected: 'Total Money Collected',
    totalShopProfit: 'Total Combined Profit',
    tailoringStream: 'Tailoring Orders',
    retailStream: 'Retail Products Sales',
    combinedStream: 'Combined Overview',
    moneyCollectedBreakdown: 'Collected Money Breakdown',
    retailRecords: 'Retail Sales Records',
    viewRetailSales: 'View Retail Sales',
    allRecords: 'All Transactions',
    tailorRecords: 'Tailoring Records',
    quickPrintSlip: 'Print Slip',
    totalRetailSales: 'Total Retail Sales',
    todaysRetailRevenue: "Today's Retail Revenue",
    customSellingPrice: 'Flexible Selling Price',

    // Expenses
    expenses: 'Shop Expenses',
    expensesNav: 'Expenses & Costs',
    addExpense: 'Add New Expense',
    editExpense: 'Edit Expense',
    expenseTitle: 'Expense Name / Title',
    expenseAmount: 'Amount',
    expenseDate: 'Date',
    spentBy: 'Spent By (Person Name)',
    expenseCategory: 'Category',
    paymentMethod: 'Payment Method',
    totalExpenses: 'Total Expenses',
    thisMonthExpenses: 'This Month Expenses',
    todayExpenses: "Today's Expenses",
    averageExpense: 'Average Expense',
    expenseReceiptNo: 'Receipt / Voucher #',
    expenseNotes: 'Additional Notes',
    categoryRent: 'Shop Rent',
    categoryUtilities: 'Utilities (Electricity/Water)',
    categoryMaterials: 'Sewing Materials & Supplies',
    categoryMaintenance: 'Machine Repair & Servicing',
    categoryFood: 'Tea, Food & Hospitality',
    categorySalaries: 'Staff Wages & Advance',
    categoryTransport: 'Transport & Delivery',
    categoryMarketing: 'Advertising & Printing',
    categoryOther: 'Miscellaneous / Other',
    deleteExpense: 'Delete Expense',
    deleteExpenseConfirmTitle: 'Delete Expense & Adjust Money Back',
    deleteExpenseConfirmMessage: 'Deleting this expense will permanently remove the record and automatically adjust the money back into your shop cash balance.',
    moneyAdjustedNotice: 'Amount Adjusted Back to Balance',
    moneyRefundedToast: 'Expense deleted successfully! Amount adjusted back to shop funds.',
    netShopBalance: 'Net Cash in Shop',
    netProfit: 'Net Shop Profit',
    totalInflows: 'Total Collected Inflows',
  },

  fa: {
    appName: 'مجیب افغان خیاطي او رخت پلورنځی',
    appSubtitle: 'سیستم جامع مدیریت سفارشات، اندازه‌ها و مشتریان',
    save: 'ذخیره',
    cancel: 'انصراف',
    delete: 'حذف',
    edit: 'ویرایش',
    close: 'بستن',
    search: 'جستجو',
    searchPlaceholder: 'جستجو بر اساس نام مشتری، شماره تماس، شماره بل یا تاریخ...',
    filter: 'فیلتر',
    all: 'همه',
    actions: 'عملیات',
    print: 'چاپ بل / رسید',
    downloadPdf: 'دانلود PDF',
    shareWhatsApp: 'ارسال به واتساپ',
    status: 'وضعیت',
    date: 'تاریخ',
    deliveryDate: 'تاریخ تحویل / تسلیمی',
    returnDate: 'تاریخ واپسی',
    created: 'ثبت شده',
    notes: 'یادداشت‌ها',
    details: 'جزئیات',
    back: 'بازگشت',
    yes: 'بله',
    no: 'نخیر',
    loading: 'در حال بارگذاری...',
    success: 'موفقانه انجام شد',
    savedSuccessfully: 'با موفقیت ذخیره شد',
    deletedSuccessfully: 'با موفقیت حذف شد',
    confirmDelete: 'آیا از حذف این مورد اطمینان دارید؟',
    areYouSure: 'این عمل غیرقابل برگشت می‌باشد.',
    noDataFound: 'هیچ ریکاردی یافت نشد',
    viewDetails: 'مشاهده جزئیات',
    required: 'ضروری',
    optional: 'اختیاری',

    dashboard: 'داشبورد فرمایشات',
    newOrder: 'ثبت فرمایش جدید',
    customers: 'فهرست مشتریان',
    fabrics: 'موجودی رخت و تکه',
    fabricInventory: 'موجودی رخت و تکه',
    products: 'اجناس و کالاها',
    productsInventory: 'موجودی اجناس و کالا',
    designAndSettings: 'طرح‌ها و تنظیمات',
    designTemplatesNav: 'طرح‌ها و مدل‌ها',
    measurementSettingsNav: 'فیلدهای اندازه',
    shopProfileNav: 'مشخصات خیاطی و بل',
    backupNav: 'پشتیبان‌گیری دیتا',
    menu: 'منوی اصلی',

    totalOrders: 'مجموع فرمایشات',
    todaysOrders: 'سفارشات امروز',
    pendingDeliveries: 'سفارشات در انتظار تحویل',
    totalMonthlyRevenue: 'عواید مجموعی این ماه',
    pendingOrders: 'در انتظار',
    inProgressOrders: 'تحت دوخت',
    readyOrders: 'آماده تحویل',
    deliveredOrders: 'تحویل داده شده',
    totalRevenue: 'مجموع ارزش',
    totalPaid: 'مجموع وصولی',
    totalBalanceDue: 'باقیمانده کل',

    orderStatus: 'وضعیت فرمایش',
    statusPending: 'در انتظار',
    statusInProgress: 'تحت دوخت',
    statusReady: 'آماده تحویل',
    statusDelivered: 'تحویل شده',
    quickStatus: 'تغییر وضعیت سریع',
    markPending: 'تغییر به در انتظار',
    markInProgress: 'تغییر به تحت دوخت',
    markReady: 'تغییر به آماده تحویل',
    markDelivered: 'تغییر به تحویل شده',

    sortBy: 'ترتیب نمایش',
    sortNewest: 'جدیدترین‌ها اول',
    sortOldest: 'قدیمی‌ترین‌ها اول',
    sortDeliveryNearest: 'نزدیک‌ترین مهلت تحویل',
    sortDeliveryFurthest: 'دورترین مهلت تحویل',
    viewCustomerHistory: 'مشاهده سابقه مشتری',

    paymentStatus: 'وضعیت پرداخت',
    paid: 'تکمیل پرداخت شده',
    partial: 'پیش پرداخت (باقیدار)',
    unpaid: 'پرداخت نشده',
    totalAmount: 'جمله مبلغ',
    paidAmount: 'جمله پرداخت (رسید)',
    balanceRemaining: 'جمله باقیات (باقیمانده)',
    advancePayment: 'پیش پرداخت',
    updatePayment: 'تغییر پرداخت',

    customerInfo: 'معلومات مشتری',
    customerName: 'نام مشتری',
    contactNumber: 'شماره تماس',
    whatsappNumber: 'شماره واتساپ',
    orderNumber: 'شماره فرمایش (بل)',
    autoGenerated: 'اتوماتیک',
    garmentType: 'نوع لباس',
    quantity: 'تعداد (دانه/دست)',
    orderSummary: 'خلاصه فرمایش',
    measurements: 'اندازه‌گیری‌ها (انچ)',
    designAndStyle: 'طرح، مدل و استایل',
    specialNotes: 'توضیحات و فرمایشات خاص خیاطی',
    saveOrder: 'ذخیره فرمایش',
    saveAndPrint: 'ذخیره و چاپ بل',
    loadCustomerMeasurements: 'بارگذاری اندازه‌های قبلی این مشتری',
    existingCustomerFound: 'مشتری قبلی شناسایی شد! اندازه‌ها آماده بارگذاری هستند.',
    newCustomerAutoSaved: 'مشتری جدید به صورت خودکار به لیست مشتریان اضافه می‌شود.',
    quickFill: 'پر کردن سریع',

    addFabric: 'افزودن رخت جدید',
    editFabric: 'ویرایش رخت',
    fabricName: 'نام رخت / پارچه',
    fabricCode: 'کد رخت',
    fabricType: 'جنس / نوعیت رخت',
    fabricColor: 'رنگ رخت',
    pricePerMeter: 'قیمت فی متر',
    stockMeters: 'موجودی (متر)',
    inStock: 'موجود',
    lowStock: 'موجودی کم',
    outOfStock: 'ختم شده',
    selectFabric: 'انتخاب رخت',
    customerFabric: 'رخت از خود مشتری',
    fabricUsed: 'مقدار رخت (متر)',
    selectFromInventory: 'انتخاب از گدام خیاطی',
    fabricDetails: 'مشخصات رخت',
    searchFabricPlaceholder: 'جستجوی رخت بر اساس نام، کد، جنس یا رنگ...',
    meters: 'متر',

    perahanTunban: 'پیراهن و تنبان',
    waistcoat: 'واسکت',
    suit: 'دریشی / دریشی رسمی',
    coatKorti: 'کورتۍ / بالاپوش',
    kameezShalwar: 'قمیص شلوار',
    kurta: 'کورته',
    otherGarment: 'لباس متفرقه',

    qad: 'قد',
    shana: 'شانه',
    asteen: 'آستین',
    yakhan: 'یخن / کالر',
    chati: 'چاتی (سینه)',
    baghal: 'بغل',
    kamar: 'کمر',
    daman: 'دامن',
    tunban: 'تنبان',
    pacha: 'پاچه',
    surin: 'سورین',
    machDast: 'مچ دست',
    unitInches: 'انچ',

    customersList: 'فهرست مشتریان',
    customerProfile: 'پروفایل مشتری',
    totalOrdersCount: 'تعداد کل فرمایشات',
    lastOrderDate: 'آخرین فرمایش',
    savedMeasurements: 'اندازه‌های ثبت شده',
    createNewOrderForCustomer: 'فرمایش جدید با این اندازه‌ها',
    customerHistory: 'تاریخچه فرمایشات',
    searchCustomersPlaceholder: 'جستجو با نام، شماره تماس یا شماره فرمایش...',
    addNewCustomer: 'افزودن مشتری جدید',
    editCustomer: 'ویرایش مشتری',

    designTemplates: 'طرح‌ها و مدل‌های دوخت',
    manageDesignCategories: 'مدیریت و افزودن انواع استایل و مدل‌ها',
    addCategory: 'افزودن دسته استایل',
    categoryTitle: 'عنوان دسته استایل',
    addOption: 'افزودن گزینه مدل',
    optionName: 'نام مدل / طرح',
    measurementSettings: 'تنظیمات فیلدهای اندازه',
    addMeasurementField: 'افزودن فیلد اندازه جدید',
    shopProfile: 'مشخصات خیاطی و سربرگ بل',
    shopName: 'نام خیاطی',
    shopAddress: 'آدرس خیاطی',
    phones: 'شماره‌های تماس',
    receiptFooter: 'متن پایانی بل',
    currency: 'واحد پول',
    backupAndRestore: 'پشتیبان‌گیری و بازگردانی دیتا',
    exportBackup: 'دانلود فایل پشتیبان (JSON)',
    importBackup: 'بازگردانی فایل پشتیبان',
    resetDemoData: 'بارگذاری اطلاعات نمونه',
    backupDescription: 'از تمام سفارشات، مشتریان، اندازه‌ها و مدل‌ها نسخه پشتیبان دریافت کنید.',

    tailorReceipt: 'بل و ورق اندازه خیاطی',
    tailorWorkSlip: 'برگه کارگاه خیاط',
    customerReceipt: 'قبض مشتری',
    bothSlips: 'هر دو برگه (خیاط + مشتری)',
    printTailorSlip: 'چاپ برگه خیاط',
    printCustomerReceipt: 'چاپ قبض مشتری',
    downloadTailorPdf: 'دانلود PDF خیاط',
    downloadCustomerPdf: 'دانلود PDF مشتری',
    measurementSlip: 'ورق اندازه',
    billBarcode: 'بارکود بل',
    phoneBarcode: 'بارکود مشتری',
    specs: 'مشخصات',
    shape: 'شکل',
    orderTakingDate: 'تاریخ ثبت',
    totalBill: 'جمله',
    totalRemaining: 'جمله باقیات',
    cabinetAndQty: 'تعداد و کابین',
    customerAndGarment: 'مشتری: لباس',
    a6Paper: 'کاغذ A6',
    item: 'لباس',
    qty: 'تعداد',
    price: 'قیمت',
    thankYouMessage: 'از انتخاب و اعتماد شما متشکریم!',

    // Products & Retail Inventory
    shoes: 'کفش و بوټ',
    watches: 'ساعت',
    perfume: 'عطر و ادکلن',
    purchasePrice: 'قیمت خرید',
    sellingPrice: 'قیمت فروش',
    stockQuantity: 'تعداد موجودی',
    lowStockThreshold: 'هشدار کمبود موجودی',
    sellItem: 'فروش کالا',
    sellProduct: 'فروش محصول',
    recordSale: 'ثبت فروش',
    salesHistory: 'تاریخچه فروشات',
    profit: 'فایده / مفاد',
    brand: 'برند / شرکت',
    vendor: 'عرضه‌کننده / فروشنده',
    category: 'دسته‌بندی',
    manageVendorsCategories: 'مدیریت فروشندگان و دسته‌بندی‌ها',
    createProductListing: 'ثبت کالای جدید',
    newInventoryEntry: 'ورودی جدید موجودی',
    addRemoveReusableValues: 'افزودن یا حذف مقادیر پیش‌فرض',
    addVendor: 'افزودن فروشنده',
    addBrand: 'افزودن برند',
    itemName: 'نام کالا',
    selectVendor: 'انتخاب فروشنده...',
    selectCategory: 'انتخاب دسته‌بندی...',
    selectBrand: 'انتخاب برند...',
    decidePriceNotice: 'قیمت فروش در هنگام فروش کالا تعیین می‌شود',
    addProduct: 'افزودن جنس جدید',
    editProduct: 'ویرایش مشخصات جنس',
    productName: 'نام جنس / محصول',
    initialStock: 'تعداد موجودی اولیه',
    sku: 'کد جنس (SKU)',
    description: 'توضیحات و مشخصات',
    allCategories: 'همه دسته‌ها',
    product: 'جنس',
    customer: 'مشتری',
    searchProductPlaceholder: 'جستجوی اجناس بر اساس نام، برند، کد...',
    noProductsFound: 'هیچ جنسی یافت نشد',
    quantityToSell: 'تعداد فروش',
    confirmSale: 'تأیید و ثبت فروش',
    updateProduct: 'به‌روزرسانی جنس',
    salesHistoryNav: 'تاریخچه فروشات',
    newSale: 'ثبت فروش جدید',
    lowStockAlert: 'هشدار کمبود موجودی',
    configurableThreshold: 'حد هشدار موجودی',
    revenueOverview7Days: 'نمودار عواید ۷ روز اخیر (فرمایشات در برابر فروشات)',
    dailyRevenue: 'عاید روزانه',
    orderRevenue: 'عاید فرمایشات خیاطی',
    productSalesRevenue: 'عاید فروش اجناس',
    customerHistoryDetails: 'سابقه و تاریخچه معاملات مشتری',
    tailorOrdersHistory: 'تاریخچه فرمایشات خیاطی',
    retailPurchasesHistory: 'اجناس و اقلام خریداری شده',
    totalSpent: 'مجموعه مصارف مشتری',

    loginTitle: 'ورود به مجیب افغان خیاطي و رخت‌فروشی',
    loginSubtitle: 'برای دسترسی به سیستم، مشخصات خود را وارد نمایید',
    email: 'آدرس ایمیل',
    password: 'رمز عبور (پسورد)',
    signInBtn: 'ورود به سیستم',
    signOut: 'خروج از حساب',
    invalidCredentials: 'ایمیل یا رمز عبور وارد شده نادرست است.',
    quickLoginAdmin: 'تکمیل خودکار اطلاعات مدیر',
    loggedInAs: 'وارد شده به عنوان',
    adminAccount: 'حساب مدیر خیاطی',
    printFormat: 'نوع چاپ',
    standardA4: 'سند استاندارد A4',
    thermal58: 'پرینتر حرارتی ۵۸ میلی‌متر',
    thermal80: 'پرینتر حرارتی ۸۰ میلی‌متر',

    garmentTypesNav: 'دسته‌بندی لباس‌ها',
    garmentCategory: 'کتگوری لباس',
    allGarments: 'تمام لباس‌ها (عمومی)',
    editMeasurementField: 'ویرایش فیلد اندازه‌گیری',
    fieldNameEn: 'نام فیلد (انگلیسی)',
    fieldNameFa: 'نام فیلد (دری)',
    fieldNamePs: 'نام فیلد (پښتو)',
    defaultVal: 'مقدار پیش‌فرض',
    stepIncrement: 'مرحله افزایش (Step)',
    isRequired: 'فیلد الزامی / ضروری',
    addDesignCategory: 'افزودن بخش دیزاین جدید',
    editDesignCategory: 'ویرایش بخش دیزاین',
    optionNameEn: 'نام گزینه (انگلیسی)',
    optionNameFa: 'نام گزینه (دری)',
    optionNamePs: 'نام گزینه (پښتو)',
    garmentTypeSelect: 'انتخاب نوع لباس',
    itemPeranTonban: 'پیراهن و تنبان (افغانی)',
    itemWasoat: 'واسکت (واسکټ)',
    itemShirt: 'قمیص (پیراهن آستین‌دار)',
    itemKurta: 'کرته (کورته)',
    itemTwoPiece: 'دو تکه (ست دو پارچه)',
    itemSuit: 'دریشی (کوت و پتلون)',
    itemCoatKorti: 'کرتی (کوت تک)',
    itemOther: 'سایر فرمایشات',
    saveMeasurementFieldBtn: 'ذخیره فیلد اندازه',
    selectGarmentTypePrompt: 'برای مشتری چه نوع لباسی دوخته می‌شود؟',
    garmentSpecificFields: 'اندازه‌ها و دیزاین‌های اختصاصی هر نوع لباس',
    manageGarmentsSubTab: 'انواع لباس‌ها',
    filterByGarment: 'فیلتر بر اساس نوع لباس',
    addGarmentType: 'افزودن نوع لباس جدید',
    editGarmentType: 'ویرایش نوع لباس',
    garmentTypeNameEn: 'نام لباس (انگلیسی)',
    garmentTypeNameFa: 'نام لباس (دری)',
    garmentTypeNamePs: 'نام لباس (پښتو)',

    // Reports & Business Streams
    reportsNav: 'گزارشات و تحلیل مالی',
    tailorRevenue: 'عواید فرمایشات خیاطی',
    tailorCollected: 'پول نقد دریافت شده خیاطی',
    tailorBalance: 'باقیمانده طلبات خیاطی',
    tailorProfit: 'مفاد خالص خیاطی',
    retailRevenue: 'عواید فروشات پرچون',
    retailCollected: 'پول نقد دریافت شده پرچون',
    retailCost: 'قیمت خرید اجناس (هزینه)',
    retailProfit: 'مفاد خالص پرچون',
    totalShopRevenue: 'مجموع کل عواید دکان',
    totalShopCollected: 'مجموع کل پول جمع‌آوری شده',
    totalShopProfit: 'مجموع کل مفاد خالص',
    tailoringStream: 'سفارشات خیاطی',
    retailStream: 'فروشات پرچون',
    combinedStream: 'گزارش مجموعی',
    moneyCollectedBreakdown: 'تفکیک پول جمع‌آوری شده',
    retailRecords: 'لیست معاملات پرچون',
    viewRetailSales: 'مشاهده فروشات پرچون',
    allRecords: 'همه معاملات',
    tailorRecords: 'سفارشات خیاطی',
    quickPrintSlip: 'چاپ بل',
    totalRetailSales: 'مجموع فروشات پرچون',
    todaysRetailRevenue: 'عواید امروز پرچون',
    customSellingPrice: 'قیمت فروش دلخواه',

    // Expenses
    expenses: 'مصارف دکان',
    expensesNav: 'مدیریت مصارف و هزینه‌ها',
    addExpense: 'ثبت مصارف جدید',
    editExpense: 'ویرایش مصرف',
    expenseTitle: 'نام / عنوان مصرف',
    expenseAmount: 'مبلغ هزینه',
    expenseDate: 'تاریخ مصرف',
    spentBy: 'نام شخص پرداخت‌کننده / مصرف‌کننده',
    expenseCategory: 'کتگوری مصرف',
    paymentMethod: 'نحوه پرداخت',
    totalExpenses: 'مجموع مصارف ثبت شده',
    thisMonthExpenses: 'مصارف این ماه',
    todayExpenses: 'مصارف امروز',
    averageExpense: 'میانگین هر مصرف',
    expenseReceiptNo: 'شماره سند / رسید',
    expenseNotes: 'توضیحات و جزئیات اضافه',
    categoryRent: 'کرایه دکان',
    categoryUtilities: 'برق و آب و خدمات',
    categoryMaterials: 'لوازم خیاطی، تار و سوزن',
    categoryMaintenance: 'سرویس و ترمیم ماشین‌آلات',
    categoryFood: 'چای، نان و مهمانداری',
    categorySalaries: 'معاشات و مساعده شاگردان',
    categoryTransport: 'کرایه رفت‌وآمد و باربری',
    categoryMarketing: 'تبلیغات و چاپ کارت',
    categoryOther: 'متفرقه و سایر مصارف',
    deleteExpense: 'حذف مصرف',
    deleteExpenseConfirmTitle: 'حذف مصرف و برگشت پول به دخل',
    deleteExpenseConfirmMessage: 'با حذف این قلم مصرف، سند باطل گردیده و مبلغ آن دوباره به موجودی نقدی و دخل دکان بازگردانده می‌شود.',
    moneyAdjustedNotice: 'برگشت پول به دخل دکان',
    moneyRefundedToast: 'مصرف حذف گردید و مبلغ با موفقیت به دخل دکان برگشت داده شد.',
    netShopBalance: 'موجودی خالص دخل',
    netProfit: 'فایده خالص دکان',
    totalInflows: 'مجموع عواید دریافتی',
  },

  ps: {
    appName: 'مجیب افغان خیاطي او رخت پلورنځی',
    appSubtitle: 'د فرمایشونو، اندازو او پیرودونکو د مدیریت جامع سیستم',
    save: 'ساتل / ثبت',
    cancel: 'ردول',
    delete: 'ړنګول',
    edit: 'سمول',
    close: 'بندول',
    search: 'پلټنه',
    searchPlaceholder: 'د پېرودونکي نوم، ټلیفون، بِل نمبر یا نېټه وپلټئ...',
    filter: 'فلټر',
    all: 'ټول',
    actions: 'کړنې',
    print: 'د بِل چاپ',
    downloadPdf: 'د پی ډي ایف ډاونلوډ',
    shareWhatsApp: 'واټساپ ته لېږل',
    status: 'حالت',
    date: 'نېټه',
    deliveryDate: 'د تسلیمۍ نېټه',
    returnDate: 'د واپسی نېټه',
    created: 'جوړ شوی',
    notes: 'یادښتونه',
    details: 'تفصیلات',
    back: 'شاته',
    yes: 'هو',
    no: 'نه',
    loading: 'د بارېدو په حال کې...',
    success: 'په بریالیتوب سره وشو',
    savedSuccessfully: 'په بریالیتوب سره ثبت شو',
    deletedSuccessfully: 'په بریالیتوب سره ړنګ شو',
    confirmDelete: 'ایا غواړئ دا ریکارډ ړنګ کړئ؟',
    areYouSure: 'دا عمل بېرته نه ګرځي.',
    noDataFound: 'هیڅ ریکارډ ونه موندل شو',
    viewDetails: 'تفصیل کتل',
    required: 'اړین',
    optional: 'اختیاري',

    dashboard: 'د فرمایشونو ډشبورډ',
    newOrder: 'نوی فرمایش',
    customers: 'د پېرودونکو لړلیک',
    fabrics: 'د رختونو زېرمه (ګدام)',
    fabricInventory: 'د رختونو زېرمه',
    products: 'جنسونه او توکي',
    productsInventory: 'د جنسونو زېرمه',
    designAndSettings: 'ډیزاینونه او تنظیمات',
    designTemplatesNav: 'ډیزاینونه او بېلګې',
    measurementSettingsNav: 'د اندازو فیلډونه',
    shopProfileNav: 'د هټۍ مشخصات او بِل',
    backupNav: 'بیک اپ او ساتنه',
    menu: 'اصلي مینو',

    totalOrders: 'ټول فرمایشونه',
    todaysOrders: 'د نن ورځې ټول فرمایشونه',
    pendingDeliveries: 'نا تسلیم شوي / چمتو فرمایشونه',
    totalMonthlyRevenue: 'د دې میاشتې ټول عواید',
    pendingOrders: 'په تمه',
    inProgressOrders: 'تر کار لاندې',
    readyOrders: 'چمتو شوي',
    deliveredOrders: 'تسلیم شوي',
    totalRevenue: 'ټول ارزښت',
    totalPaid: 'ترلاسه شوې روپۍ',
    totalBalanceDue: 'ټولې پاتې روپۍ',

    orderStatus: 'د فرمایش حالت',
    statusPending: 'په تمه',
    statusInProgress: 'تر ګنډلو لاندې',
    statusReady: 'چمتو شوی',
    statusDelivered: 'تسلیم شوی',
    quickStatus: 'د وضعیت چټک بدلون',
    markPending: 'په تمه حالت ته اړول',
    markInProgress: 'تر کار لاندې حالت ته اړول',
    markReady: 'چمتو شوي حالت ته اړول',
    markDelivered: 'تسلیم شوي حالت ته اړول',

    sortBy: 'ترتیب پر اساس',
    sortNewest: 'تر ټولو نوي لومړی',
    sortOldest: 'تر ټولو پخواني لومړی',
    sortDeliveryNearest: 'د تحویل نږدې نېټه',
    sortDeliveryFurthest: 'د تحویل لرې نېټه',
    viewCustomerHistory: 'د پېرودونکي تاریخچه کتل',

    paymentStatus: 'د پیسو حالت',
    paid: 'بشپړ ورکړل شوی',
    partial: 'بیعانه (پاتې لری)',
    unpaid: 'نه دی ورکړل شوی',
    totalAmount: 'جمله روپۍ',
    paidAmount: 'جمله پرداخت (رسید)',
    balanceRemaining: 'جمله باقیات (پاتې)',
    advancePayment: 'بیعانه / مخکې ورکړه',
    updatePayment: 'د پیسو بدلون',

    customerInfo: 'د پېرودونکي معلومات',
    customerName: 'د پېرودونکي نوم',
    contactNumber: 'د اړیکې شمېره',
    whatsappNumber: 'د واټساپ شمېره',
    orderNumber: 'د بِل / فرمایش شمېره',
    autoGenerated: 'اتومات',
    garmentType: 'د جامو ډول',
    quantity: 'تعداد (جوړه/دانه)',
    orderSummary: 'د فرمایش لنډیز',
    measurements: 'اندازې (انچ)',
    designAndStyle: 'ډیزاین، استایل او شیپ',
    specialNotes: 'د خیاطۍ ځانګړي یادښتونه',
    saveOrder: 'فرمایش ثبت کړئ',
    saveAndPrint: 'ثبت او بِل چاپ کړئ',
    loadCustomerMeasurements: 'د دې مشتري پخوانۍ اندازې راواخلئ',
    existingCustomerFound: 'پخوانی مشتري وپېژندل شو! اندازې چمتو دي.',
    newCustomerAutoSaved: 'نوی مشتري به په اتومات ډول د پیرودونکو لړۍ ته اضافه شي.',
    quickFill: 'چټک ډکول',

    addFabric: 'نوی رخت ورزیات کړئ',
    editFabric: 'رخت سم کړئ',
    fabricName: 'د رخت نوم',
    fabricCode: 'د رخت کوډ',
    fabricType: 'د رخت ډول / مواد',
    fabricColor: 'د رخت رنګ',
    pricePerMeter: 'فی متر بیه',
    stockMeters: 'موجوده ذخیره (متره)',
    inStock: 'موجود دی',
    lowStock: 'لږ پاتې',
    outOfStock: 'ختم شوی',
    selectFabric: 'رخت وټاکئ',
    customerFabric: 'د مشتري خپل رخت',
    fabricUsed: 'کارېدلی رخت (متره)',
    selectFromInventory: 'د هټۍ له ذخیرې څخه انتخاب',
    fabricDetails: 'د رخت تفصیلات',
    searchFabricPlaceholder: 'د رخت نوم، کوډ، رنګ یا ډول پلټل...',
    meters: 'متره',

    perahanTunban: 'پیراهن او تنبان (ګنډل شوې جامې)',
    waistcoat: 'واسکت',
    suit: 'دریشي / رسمي کالي',
    coatKorti: 'کورتۍ / واسکټ کوټ',
    kameezShalwar: 'قمیص شلوار',
    kurta: 'کورته',
    otherGarment: 'نورې جامې',

    qad: 'قد',
    shana: 'شانه',
    asteen: 'آستین',
    yakhan: 'یخن / کالر',
    chati: 'چاتی (سینه)',
    baghal: 'بغل',
    kamar: 'کمر',
    daman: 'دامن',
    tunban: 'تنبان / پرتوګ',
    pacha: 'پاچه',
    surin: 'سورین',
    machDast: 'مچ لاس',
    unitInches: 'انچ',

    customersList: 'د پېرودونکو لړلیک',
    customerProfile: 'د مشتري پېژندنه',
    totalOrdersCount: 'د فرمایشونو شمېر',
    lastOrderDate: 'وروستی فرمایش',
    savedMeasurements: 'ساتل شوې اندازې',
    createNewOrderForCustomer: 'په دې اندازو نوی فرمایش',
    customerHistory: 'د فرمایشونو تاریخچه',
    searchCustomersPlaceholder: 'د نوم، ټلیفون یا فرمایش نمبر له مخې پلټنه...',
    addNewCustomer: 'نوی مشتري ورزیات کړئ',
    editCustomer: 'مشتري سم کړئ',

    designTemplates: 'ډیزاینونه او بېلګې',
    manageDesignCategories: 'د ډیزاینونو او استایلونو مدیریت',
    addCategory: 'د ډیزاین نوې برخه',
    categoryTitle: 'د برخې نوم',
    addOption: 'د موډل اختیار',
    optionName: 'د موډل / استایل نوم',
    measurementSettings: 'د اندازو فیلډونه',
    addMeasurementField: 'د نوې اندازې فیلډ',
    shopProfile: 'د هټۍ مشخصات او د بِل سرلیک',
    shopName: 'د خیاطۍ نوم',
    shopAddress: 'د خیاطۍ پته',
    phones: 'د اړیکې شمېرې',
    receiptFooter: 'د بِل پایلیک',
    currency: 'د پیسو واحد',
    backupAndRestore: 'بیک اپ او د معلوماتو ساتنه',
    exportBackup: 'د بیک اپ ډاونلوډ (JSON)',
    importBackup: 'د بیک اپ بېرته راوستل',
    resetDemoData: 'نمونه معلومات راوستل',
    backupDescription: 'د ټولو فرمایشونو، پېرودونکو، اندازو او ډیزاینونو بیک اپ فایل ترلاسه کړئ.',

    tailorReceipt: 'د خیاطۍ بِل او د اندازې پرچه',
    tailorWorkSlip: 'د خیاط کاري پرچه',
    customerReceipt: 'د پیرودونکي رسید',
    bothSlips: 'دواړه پاڼې (خیاط + پېرودونکی)',
    printTailorSlip: 'د خیاط پاڼه چاپ کړئ',
    printCustomerReceipt: 'د پیرودونکي رسید چاپ کړئ',
    downloadTailorPdf: 'د خیاط PDF ډاونلوډ',
    downloadCustomerPdf: 'د پیرودونکي PDF ډاونلوډ',
    measurementSlip: 'د اندازې پرچه',
    billBarcode: 'د بِل بارکوډ',
    phoneBarcode: 'د پیرودونکي بارکوډ',
    specs: 'ځانګړنې',
    shape: 'شکل / بڼه',
    orderTakingDate: 'د ثبت نېټه',
    totalBill: 'جمله (ټول)',
    totalRemaining: 'جمله باقیات (پاتې)',
    cabinetAndQty: 'تعداد او کابین',
    customerAndGarment: 'پېرودونکی: کالي',
    a6Paper: 'A6 پاڼه',
    item: 'کالي',
    qty: 'تعداد',
    price: 'قیمت',
    thankYouMessage: 'ستاسو له باور او راتګ څخه مننه!',

    // Products & Retail Inventory
    shoes: 'بوټان او چپلی',
    watches: 'ساعتونه',
    perfume: 'عطر او خوشبويي',
    purchasePrice: 'د پیرودلو بیه',
    sellingPrice: 'د خرڅلاو بیه',
    stockQuantity: 'د موجودي شمېر',
    lowStockThreshold: 'د کموالي خبرداری',
    sellItem: 'د توکي خرڅول',
    sellProduct: 'جنس خرڅول',
    recordSale: 'د خرڅلاو ثبت',
    salesHistory: 'د خرڅلاو تاریخچه',
    profit: 'ګټه / مفاد',
    brand: 'برانډ / شرکت',
    vendor: 'عرضه کوونکی / پلورونکی',
    category: 'کټګوري / وېشنیزه',
    manageVendorsCategories: 'د عرضه کوونکو او وېشنیزو سمبالښت',
    createProductListing: 'د نوي جنس اضافه کول',
    newInventoryEntry: 'نوی جنس',
    addRemoveReusableValues: 'د ارزښتونو زیاتول یا ړنګول',
    addVendor: 'عرضه کوونکی زیاتول',
    addBrand: 'برانډ زیاتول',
    itemName: 'د جنس نوم',
    selectVendor: 'عرضه کوونکی وټاکئ...',
    selectCategory: 'وېشنیزه وټاکئ...',
    selectBrand: 'برانډ وټاکئ...',
    decidePriceNotice: 'د خرڅلاو بیه د خرڅلاو پر مهال ټاکل کېږي',
    addProduct: 'نوی جنس ورزیاتول',
    editProduct: 'د جنس تدوین',
    productName: 'د جنس نوم',
    initialStock: 'لومړنی موجودیت',
    sku: 'د جنس کوډ (SKU)',
    description: 'تفصیلات او ځانګړتیاوې',
    allCategories: 'ټولې کټګورۍ',
    product: 'جنس',
    customer: 'پیرودونکی',
    searchProductPlaceholder: 'د توکو پلټنه د نوم، برانډ یا کوډ له مخې...',
    noProductsFound: 'هیڅ جنس ونه موندل شو',
    quantityToSell: 'د خرڅلاو شمېر',
    confirmSale: 'د پلور بشپړول',
    updateProduct: 'جنس تازه کول',
    salesHistoryNav: 'د خرڅلاو تاریخچه',
    newSale: 'نوی پلور ثبتول',
    lowStockAlert: 'د کموالي خبرداری',
    configurableThreshold: 'د کموالي حد',
    revenueOverview7Days: 'د تېرو ۷ ورځو عاید (فرمایشونه او پرچون پلور)',
    dailyRevenue: 'ورځنی عاید',
    orderRevenue: 'د خیاطۍ عاید',
    productSalesRevenue: 'د پرچون پلور عاید',
    customerHistoryDetails: 'د مشتري د راکړې ورکړې تاریخچه',
    tailorOrdersHistory: 'د خیاطۍ فرمایشونه',
    retailPurchasesHistory: 'پېرل شوي توکي او اجناس',
    totalSpent: 'د مشتري ټول مصرف',

    loginTitle: 'مجیب افغان خیاطي او رخت پلورنځي ته ننوتل',
    loginSubtitle: 'سیستم ته د لاسرسي لپاره خپل معلومات دننه کړئ',
    email: 'د بریښنالیک پته',
    password: 'پټنوم (پاسورډ)',
    signInBtn: 'سیستم ته ننوتل',
    signOut: 'له حساب څخه وتل',
    invalidCredentials: 'بریښنالیک یا پټنوم ناسم دی. مهرباني وکړئ معلومات وګورئ.',
    quickLoginAdmin: 'د اډمین معلومات اتومات ډکول',
    loggedInAs: 'ننوتلی یاست لکه',
    adminAccount: 'د خیاطۍ د مدیر حساب',
    printFormat: 'د چاپ ډول',
    standardA4: 'معیاري A4 سند',
    thermal58: 'حرارتي ۵۸ ملي متره',
    thermal80: 'حرارتي ۸۰ ملي متره',

    garmentTypesNav: 'د جامو وېشنیزې',
    garmentCategory: 'د جامو کټګوري',
    allGarments: 'ټول کالي (عمومي)',
    editMeasurementField: 'د اندازې فیلډ سمول',
    fieldNameEn: 'د فیلډ نوم (انګلیسي)',
    fieldNameFa: 'د فیلډ نوم (دري)',
    fieldNamePs: 'د فیلډ نوم (پښتو)',
    defaultVal: 'اصلي (ډیفالټ) اندازه',
    stepIncrement: 'د زیاتوالي ګام (Step)',
    isRequired: 'اړین / لازمي فیلډ',
    addDesignCategory: 'د نوي ډیزاین برخه زیاتول',
    editDesignCategory: 'د ډیزاین برخه سمول',
    optionNameEn: 'د غوره توب نوم (انګلیسي)',
    optionNameFa: 'د غوره توب نوم (دري)',
    optionNamePs: 'د غوره توب نوم (پښتو)',
    garmentTypeSelect: 'د جامو ډول وټاکئ',
    itemPeranTonban: 'پیرهن او پرتوګ (افغاني کالي)',
    itemWasoat: 'واسکټ',
    itemShirt: 'کمیس (لستوڼي لرونکی)',
    itemKurta: 'کورته',
    itemTwoPiece: 'دوه ټوټې ست کالي',
    itemSuit: 'دریشي (کوت او پتلون)',
    itemCoatKorti: 'کورټۍ (کوت)',
    itemOther: 'نور فرمایشونه',
    saveMeasurementFieldBtn: 'د اندازې فیلډ خوندي کول',
    selectGarmentTypePrompt: 'د پیرودونکي لپاره کوم ډول کالي ګنډل کېږي؟',
    garmentSpecificFields: 'د هر ډول کالیو لپاره ځانګړې اندازې او ډیزاینونه',
    manageGarmentsSubTab: 'د کاليو ډولونه',
    filterByGarment: 'د کاليو د ډول له مخې فلټر',
    addGarmentType: 'د کالیو نوی ډول زیاتول',
    editGarmentType: 'د کالیو ډول سمول',
    garmentTypeNameEn: 'د جامو نوم (انګلیسي)',
    garmentTypeNameFa: 'د جامو نوم (دري)',
    garmentTypeNamePs: 'د جامو نوم (پښتو)',

    // Reports & Business Streams
    reportsNav: 'راپورونه او مالي شننه',
    tailorRevenue: 'د خیاطۍ د فرمایشونو عواید',
    tailorCollected: 'د خیاطۍ راټولې شوې نغدې پیسې',
    tailorBalance: 'د خیاطۍ پاتې پیسې',
    tailorProfit: 'د خیاطۍ خالص مفاد',
    retailRevenue: 'د پرچون پلور عواید',
    retailCollected: 'د پرچون راټولې شوې پیسې',
    retailCost: 'د توکو د پېرلو بیه (لګښت)',
    retailProfit: 'د پرچون خالص مفاد',
    totalShopRevenue: 'د هټۍ ټول عواید',
    totalShopCollected: 'ټولې راټولې شوې نغدې پیسې',
    totalShopProfit: 'ټول خالص مفاد',
    tailoringStream: 'د خیاطۍ فرمایشونه',
    retailStream: 'د پرچون پلور',
    combinedStream: 'عمومي راپور',
    moneyCollectedBreakdown: 'د راټولو شویو پیسو تفکیک',
    retailRecords: 'د پرچون پلور ریکارډونه',
    viewRetailSales: 'د پرچون پلور لیدل',
    allRecords: 'ټولې معاملې',
    tailorRecords: 'د خیاطۍ ریکارډونه',
    quickPrintSlip: 'د بِل چاپ',
    totalRetailSales: 'د پرچون ټول پلور',
    todaysRetailRevenue: 'د نن ورځې پرچون عواید',
    customSellingPrice: 'خپله خوښه د پلور بیه',

    // Expenses
    expenses: 'د دوکان لګښتونه',
    expensesNav: 'لګښتونه او مصارف',
    addExpense: 'نوی لګښت ثبتول',
    editExpense: 'د لګښت سمول',
    expenseTitle: 'د لګښت نوم / تفصیل',
    expenseAmount: 'د لګښت پیسې / رقم',
    expenseDate: 'نېټه',
    spentBy: 'د لګوونکي / مصرف کوونکي کس نوم',
    expenseCategory: 'د لګښت برخه / کټګوري',
    paymentMethod: 'د تادیې طریقه',
    totalExpenses: 'ټول لګښتونه',
    thisMonthExpenses: 'د دې میاشتې لګښتونه',
    todayExpenses: 'د نن ورځې لګښتونه',
    averageExpense: 'د هر لګښت اوسط',
    expenseReceiptNo: 'د بِل / سَنَد نمبر',
    expenseNotes: 'اضافي یادښتونه',
    categoryRent: 'د دوکان کرایه',
    categoryUtilities: 'برېښنا او اوبه',
    categoryMaterials: 'د خیاطۍ سامان، تار او ستنې',
    categoryMaintenance: 'د ګنډلو ماشین ترمیم او سرویس',
    categoryFood: 'چای، ډوډۍ او مېلمستیا',
    categorySalaries: 'معاشات او پیشکي پیسې',
    categoryTransport: 'کرایه او باربري',
    categoryMarketing: 'تبلیغات او چاپ',
    categoryOther: 'نور / متفرقه لګښتونه',
    deleteExpense: 'د لګښت ړنګول',
    deleteExpenseConfirmTitle: 'د لګښت ړنګول او نغدو پیسو بېرته اضافه کول',
    deleteExpenseConfirmMessage: 'د دې لګښت په ړنګولو سره به سند لغوه شي او پیسې به بېرته د دوکان نغدو پیسو (دخل) ته ورزیاتې شي.',
    moneyAdjustedNotice: 'پیسې بېرته دخل ته ورزیاتې شوې',
    moneyRefundedToast: 'لګښت ړنګ شو او پیسې بېرته د دوکان حساب ته اضافه شوې.',
    netShopBalance: 'د دخل خالص موجودي',
    netProfit: 'د دوکان خالصه ګټه',
    totalInflows: 'ټولې ترلاسه شوې پیسې',
  },
};
